config/routes.rb
Rails.application.routes.draw do
  resources :departments  do
    resources :members
    resources :apparatus
    resources :alarms	
  end
  resources :member_types
  get 'welcome/index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/alarm.rb
class Alarm < ApplicationRecord
  belongs_to :department
end

app/controllers/alarms_controller.rb
class AlarmsController < ApplicationController
  before_action :set_alarm, only: [:show, :edit, :update, :destroy]

  # GET /alarms
  # GET /alarms.json
  def index
    @alarms = Alarm.all
  end

  # GET /alarms/1
  # GET /alarms/1.json
  def show
  end

  # GET /alarms/new
  def new
    @alarm = Alarm.new
  end

  # GET /alarms/1/edit
  def edit
  end

  # POST /alarms
  # POST /alarms.json
  def create
    @alarm = Alarm.new(alarm_params)

    respond_to do |format|
      if @alarm.save
        format.html { redirect_to @alarm, notice: 'Alarm was successfully created.' }
        format.json { render :show, status: :created, location: @alarm }
      else
        format.html { render :new }
        format.json { render json: @alarm.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /alarms/1
  # PATCH/PUT /alarms/1.json
  def update
    respond_to do |format|
      if @alarm.update(alarm_params)
        format.html { redirect_to @alarm, notice: 'Alarm was successfully updated.' }
        format.json { render :show, status: :ok, location: @alarm }
      else
        format.html { render :edit }
        format.json { render json: @alarm.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /alarms/1
  # DELETE /alarms/1.json
  def destroy
    @alarm.destroy
    respond_to do |format|
      format.html { redirect_to alarms_url, notice: 'Alarm was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_alarm
      @alarm = Alarm.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def alarm_params
      params.require(:alarm).permit(:department_id, :date, :location, :received, :ten_8, :ten_2, :ten_7, :miles)
    end
end

app/helpers/alarms_helper.rb
module AlarmsHelper
end

app/views/alarms/_form.html.erb
<%= form_for(alarm) do |f| %>
  <% if alarm.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(alarm.errors.count, "error") %> prohibited this alarm from being saved:</h2>

      <ul>
      <% alarm.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :department_id %>
    <%= f.text_field :department_id %>
  </div>

  <div class="field">
    <%= f.label :date %>
    <%= f.date_select :date %>
  </div>

  <div class="field">
    <%= f.label :location %>
    <%= f.text_field :location %>
  </div>

  <div class="field">
    <%= f.label :received %>
    <%= f.datetime_select :received %>
  </div>

  <div class="field">
    <%= f.label :ten_8 %>
    <%= f.datetime_select :ten_8 %>
  </div>

  <div class="field">
    <%= f.label :ten_2 %>
    <%= f.datetime_select :ten_2 %>
  </div>

  <div class="field">
    <%= f.label :ten_7 %>
    <%= f.datetime_select :ten_7 %>
  </div>

  <div class="field">
    <%= f.label :miles %>
    <%= f.number_field :miles %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/alarms/edit.html.erb
<h1>Editing Alarm</h1>

<%= render 'form', alarm: @alarm %>

<%= link_to 'Show', @alarm %> |
<%= link_to 'Back', alarms_path %>

app/views/alarms/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Alarms</h1>

<table>
  <thead>
    <tr>
      <th>Department</th>
      <th>Date</th>
      <th>Location</th>
      <th>Received</th>
      <th>10 8</th>
      <th>10 2</th>
      <th>10 7</th>
      <th>Miles</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @alarms.each do |alarm| %>
      <tr>
        <td><%= alarm.department %></td>
        <td><%= alarm.date %></td>
        <td><%= alarm.location %></td>
        <td><%= alarm.received %></td>
        <td><%= alarm.ten_8 %></td>
        <td><%= alarm.ten_2 %></td>
        <td><%= alarm.ten_7 %></td>
        <td><%= alarm.miles %></td>
        <td><%= link_to 'Show', alarm %></td>
        <td><%= link_to 'Edit', edit_alarm_path(alarm) %></td>
        <td><%= link_to 'Destroy', alarm, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Alarm', new_alarm_path %>

app/views/alarms/new.html.erb
<h1>New Alarm</h1>

<%= render 'form', alarm: @alarm %>

<%= link_to 'Back', alarms_path %>

app/views/alarms/show.html.erb
<p>
  <strong>Department:</strong>
  <%= @alarm.department %>
</p>

<p>
  <strong>Date:</strong>
  <%= @alarm.date %>
</p>

<p>
  <strong>Location:</strong>
  <%= @alarm.location %>
</p>

<p>
  <strong>Received:</strong>
  <%= @alarm.received %>
</p>

<p>
  <strong>10 8:</strong>
  <%= @alarm.ten_8 %>
</p>

<p>
  <strong>10 2:</strong>
  <%= @alarm.ten_2 %>
</p>

<p>
  <strong>10 7:</strong>
  <%= @alarm.ten_7 %>
</p>

<p>
  <strong>Miles:</strong>
  <%= @alarm.miles %>
</p>

<%= link_to 'Edit', edit_alarm_path(@alarm) %> |
<%= link_to 'Back', alarms_path %>