config/routes.rb
Rails.application.routes.draw do
  resources :departments  do
    resources :members
    resources :apparatus
    resources :alarms	
  end
  resources :member_types
  get 'welcome/index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/apparatu.rb
class Apparatu < ApplicationRecord
  belongs_to :department
end

app/controllers/apparatus_controller.rb
class ApparatusController < ApplicationController
  before_action :set_apparatu, only: [:show, :edit, :update, :destroy]

  # GET /apparatus
  # GET /apparatus.json
  def index
    @apparatus = Apparatu.all
  end

  # GET /apparatus/1
  # GET /apparatus/1.json
  def show
  end

  # GET /apparatus/new
  def new
    @apparatu = Apparatu.new
  end

  # GET /apparatus/1/edit
  def edit
  end

  # POST /apparatus
  # POST /apparatus.json
  def create
    @apparatu = Apparatu.new(apparatu_params)

    respond_to do |format|
      if @apparatu.save
        format.html { redirect_to @apparatu, notice: 'Apparatu was successfully created.' }
        format.json { render :show, status: :created, location: @apparatu }
      else
        format.html { render :new }
        format.json { render json: @apparatu.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /apparatus/1
  # PATCH/PUT /apparatus/1.json
  def update
    respond_to do |format|
      if @apparatu.update(apparatu_params)
        format.html { redirect_to @apparatu, notice: 'Apparatu was successfully updated.' }
        format.json { render :show, status: :ok, location: @apparatu }
      else
        format.html { render :edit }
        format.json { render json: @apparatu.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /apparatus/1
  # DELETE /apparatus/1.json
  def destroy
    @apparatu.destroy
    respond_to do |format|
      format.html { redirect_to apparatus_url, notice: 'Apparatu was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_apparatu
      @apparatu = Apparatu.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def apparatu_params
      params.require(:apparatu).permit(:department_id, :code, :name, :current)
    end
end

app/helpers/apparatus_helper.rb
module ApparatusHelper
end

app/views/apparatus/_form.html.erb
<%= form_for(apparatu) do |f| %>
  <% if apparatu.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(apparatu.errors.count, "error") %> prohibited this apparatu from being saved:</h2>

      <ul>
      <% apparatu.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :department_id %>
    <%= f.text_field :department_id %>
  </div>

  <div class="field">
    <%= f.label :code %>
    <%= f.number_field :code %>
  </div>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :current %>
    <%= f.check_box :current %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/apparatus/edit.html.erb
<h1>Editing Apparatu</h1>

<%= render 'form', apparatu: @apparatu %>

<%= link_to 'Show', @apparatu %> |
<%= link_to 'Back', apparatus_path %>

app/views/apparatus/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Apparatus</h1>

<table>
  <thead>
    <tr>
      <th>Department</th>
      <th>Code</th>
      <th>Name</th>
      <th>Current</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @apparatus.each do |apparatu| %>
      <tr>
        <td><%= apparatu.department %></td>
        <td><%= apparatu.code %></td>
        <td><%= apparatu.name %></td>
        <td><%= apparatu.current %></td>
        <td><%= link_to 'Show', apparatu %></td>
        <td><%= link_to 'Edit', edit_apparatu_path(apparatu) %></td>
        <td><%= link_to 'Destroy', apparatu, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Apparatu', new_apparatu_path %>

app/views/apparatus/new.html.erb
<h1>New Apparatu</h1>

<%= render 'form', apparatu: @apparatu %>

<%= link_to 'Back', apparatus_path %>

app/views/apparatus/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Department:</strong>
  <%= @apparatu.department %>
</p>

<p>
  <strong>Code:</strong>
  <%= @apparatu.code %>
</p>

<p>
  <strong>Name:</strong>
  <%= @apparatu.name %>
</p>

<p>
  <strong>Current:</strong>
  <%= @apparatu.current %>
</p>

<%= link_to 'Edit', edit_apparatu_path(@apparatu) %> |
<%= link_to 'Back', apparatus_path %>