config/routes.rb
Rails.application.routes.draw do
  resources :departments  do
    resources :members
    resources :apparatus
    resources :alarms	
  end
  resources :member_types
  get 'welcome/index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/member_types_controller.rb
class MemberTypesController < ApplicationController
  before_action :set_member_type, only: [:show, :edit, :update, :destroy]

  # GET /member_types
  # GET /member_types.json
  def index
    @member_types = MemberType.all
  end

  # GET /member_types/1
  # GET /member_types/1.json
  def show
  end

  # GET /member_types/new
  def new
    @member_type = MemberType.new
  end

  # GET /member_types/1/edit
  def edit
  end

  # POST /member_types
  # POST /member_types.json
  def create
    @member_type = MemberType.new(member_type_params)

    respond_to do |format|
      if @member_type.save
        format.html { redirect_to @member_type, notice: 'Member type was successfully created.' }
        format.json { render :show, status: :created, location: @member_type }
      else
        format.html { render :new }
        format.json { render json: @member_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /member_types/1
  # PATCH/PUT /member_types/1.json
  def update
    respond_to do |format|
      if @member_type.update(member_type_params)
        format.html { redirect_to @member_type, notice: 'Member type was successfully updated.' }
        format.json { render :show, status: :ok, location: @member_type }
      else
        format.html { render :edit }
        format.json { render json: @member_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /member_types/1
  # DELETE /member_types/1.json
  def destroy
    @member_type.destroy
    respond_to do |format|
      format.html { redirect_to member_types_url, notice: 'Member type was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_member_type
      @member_type = MemberType.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def member_type_params
      params.require(:member_type).permit(:department_id, :type)
    end
end

app/helpers/member_types_helper.rb
module MemberTypesHelper
end

app/views/member_types/_form.html.erb
<%= form_for(member_type) do |f| %>
  <% if member_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(member_type.errors.count, "error") %> prohibited this member_type from being saved:</h2>

      <ul>
      <% member_type.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :department_id %>
    <%= f.text_field :department_id %>
  </div>

  <div class="field">
    <%= f.label :type %>
    <%= f.text_field :type %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/member_types/edit.html.erb
<h1>Editing Member Type</h1>

<%= render 'form', member_type: @member_type %>

<%= link_to 'Show', @member_type %> |
<%= link_to 'Back', member_types_path %>

app/views/member_types/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Member Types</h1>

<table>
  <thead>
    <tr>
      <th>Department</th>
      <th>Type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @member_types.each do |member_type| %>
      <tr>
        <td><%= member_type.department %></td>
        <td><%= member_type.type %></td>
        <td><%= link_to 'Show', member_type %></td>
        <td><%= link_to 'Edit', edit_member_type_path(member_type) %></td>
        <td><%= link_to 'Destroy', member_type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Member Type', new_member_type_path %>

app/views/member_types/new.html.erb
<h1>New Member Type</h1>

<%= render 'form', member_type: @member_type %>

<%= link_to 'Back', member_types_path %>

app/views/member_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Department:</strong>
  <%= @member_type.department %>
</p>

<p>
  <strong>Type:</strong>
  <%= @member_type.type %>
</p>

<%= link_to 'Edit', edit_member_type_path(@member_type) %> |
<%= link_to 'Back', member_types_path %>