config/routes.rb
Rails.application.routes.draw do
  resources :departments  do
    resources :members
    resources :apparatus
    resources :alarms	
  end
  resources :member_types
  get 'welcome/index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/member.rb
class Member < ApplicationRecord
  belongs_to :department
  belongs_to :state
  belongs_to :bloodtype
end

app/models/member_type.rb
class MemberType < ApplicationRecord
  belongs_to :department
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  before_action :set_member, only: [:show, :edit, :update, :destroy]

  # GET /members
  # GET /members.json
  def index
    @department = Department.find_by_id(params[:department_id])
    @members = @department.members
  end

  # GET /members/1
  # GET /members/1.json
  def show
  end

  # GET /members/new
  def new
    department = Department.find_by_id(params[:department_id])
    @member = department.members.build
    @member.state_id = @member.department.state_id
  end

  # GET /members/1/edit
  def edit
  end

  # POST /members
  # POST /members.json
  def create
    #department = Department.find_by_id(params[:department_id])
    @member = Member.create(params[:member])

    respond_to do |format|
      if @member.save
        format.html { redirect_to [@member.department, @member], notice: 'Member was successfully created.' }
        format.json { render :show, status: :created, location: @member }
      else
        format.html { render :new }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /members/1
  # PATCH/PUT /members/1.json
  def update
    department = Department.find_by_id(params[:department_id])
    @member = department.member.find_by_id(params[:id])
    respond_to do |format|
      if @member.update(member_params)
        format.html { redirect_to [@member.department, @member], notice: 'Member was successfully updated.' }
        format.json { render :show, status: :ok, location: @member }
      else
        format.html { render :edit }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /members/1
  # DELETE /members/1.json
  def destroy
    @member.destroy
    respond_to do |format|
      format.html { redirect_to department_members_url, notice: 'Member was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_member
      @member = Member.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def member_params
      params.require(member: {})
      #params.require(:member).permit(:department_id, :name, :address, :address2, :city, :state_id, :zip, :home_phone, :cell_phone, :dept_cell_phone, :social_security, :drivers_license, :birth_date, :bloodtype_id, :email, :alarm_roster, :attendance_roster, :tax_credit)
    end
end

app/helpers/members_helper.rb
module MembersHelper
end

app/views/members/_form.html.erb
<%= form_for [@member.department, @member] do |f| %>
  <% if member.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(member.errors.count, "error") %> prohibited this member from being saved:</h2>

      <ul>
      <% member.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.hidden_field :department_id %>
  </div>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :address %>
    <%= f.text_field :address %>
  </div>

  <div class="field">
    <%= f.label :address2 %>
    <%= f.text_field :address2 %>
  </div>

  <div class="field">
    <%= f.label :city %>
    <%= f.text_field :city %>
  </div>

  <div class="field">
    <%= f.label :state_id %>
    <%= f.select :state_id, options_from_collection_for_select(State.all, :id, :abbreviation) %>
  </div>

  <div class="field">
    <%= f.label :zip %>
    <%= f.text_field :zip %>
  </div>

  <div class="field">
    <%= f.label :home_phone %>
    <%= f.text_field :home_phone %>
  </div>

  <div class="field">
    <%= f.label :cell_phone %>
    <%= f.text_field :cell_phone %>
  </div>

  <div class="field">
    <%= f.label :dept_cell_phone %>
    <%= f.text_field :dept_cell_phone %>
  </div>

  <div class="field">
    <%= f.label :social_security %>
    <%= f.text_field :social_security %>
  </div>

  <div class="field">
    <%= f.label :drivers_license %>
    <%= f.text_field :drivers_license %>
  </div>

  <div class="field">
    <%= f.label :birth_date %>
    <%= f.date_select :birth_date %>
  </div>

  <div class="field">
    <%= f.label :bloodtype_id %>
    <%= f.select :bloodtype_id, options_from_collection_for_select(BloodType.all, :id, :type) %>
  </div>

  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <div class="field">
    <%= f.label :alarm_roster %>
    <%= f.check_box :alarm_roster %>
  </div>

  <div class="field">
    <%= f.label :attendance_roster %>
    <%= f.check_box :attendance_roster %>
  </div>

  <div class="field">
    <%= f.label :tax_credit %>
    <%= f.check_box :tax_credit %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/members/edit.html.erb
<h1>Editing Member</h1>

<%= render 'form', member: @member %>

<%= link_to 'Show', @member %> |
<%= link_to 'Back', department_members_path(:department) %>

app/views/members/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Members</h1>

<table>
  <thead>
    <tr>
      <th>Department</th>
      <th>Name</th>
      <th>Address</th>
      <th>Address2</th>
      <th>City</th>
      <th>State</th>
      <th>Zip</th>
      <th>Home phone</th>
      <th>Cell phone</th>
      <th>Dept cell phone</th>
      <th>Social security</th>
      <th>Drivers license</th>
      <th>Birth date</th>
      <th>Bloodtype</th>
      <th>Email</th>
      <th>Alarm roster</th>
      <th>Attendance roster</th>
      <th>Tax credit</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @members.each do |member| %>
      <tr>
        <td><%= member.department %></td>
        <td><%= member.name %></td>
        <td><%= member.address %></td>
        <td><%= member.address2 %></td>
        <td><%= member.city %></td>
        <td><%= member.state %></td>
        <td><%= member.zip %></td>
        <td><%= member.home_phone %></td>
        <td><%= member.cell_phone %></td>
        <td><%= member.dept_cell_phone %></td>
        <td><%= member.social_security %></td>
        <td><%= member.drivers_license %></td>
        <td><%= member.birth_date %></td>
        <td><%= member.bloodtype %></td>
        <td><%= member.email %></td>
        <td><%= member.alarm_roster %></td>
        <td><%= member.attendance_roster %></td>
        <td><%= member.tax_credit %></td>
        <td><%= link_to 'Show', member %></td>
        <td><%= link_to 'Edit', edit_department_member_path(member.department, member) %></td>
        <td><%= link_to 'Destroy', member, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Member', new_department_member_path(@department) %>

app/views/members/new.html.erb
<h1>New Member</h1>

<%= render 'form', member: @member %>

<%= link_to 'Back', department_members_path(@member.department) %>

app/views/members/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Department:</strong>
  <%= @member.department %>
</p>

<p>
  <strong>Name:</strong>
  <%= @member.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @member.address %>
</p>

<p>
  <strong>Address2:</strong>
  <%= @member.address2 %>
</p>

<p>
  <strong>City:</strong>
  <%= @member.city %>
</p>

<p>
  <strong>State:</strong>
  <%= @member.state %>
</p>

<p>
  <strong>Zip:</strong>
  <%= @member.zip %>
</p>

<p>
  <strong>Home phone:</strong>
  <%= @member.home_phone %>
</p>

<p>
  <strong>Cell phone:</strong>
  <%= @member.cell_phone %>
</p>

<p>
  <strong>Dept cell phone:</strong>
  <%= @member.dept_cell_phone %>
</p>

<p>
  <strong>Social security:</strong>
  <%= @member.social_security %>
</p>

<p>
  <strong>Drivers license:</strong>
  <%= @member.drivers_license %>
</p>

<p>
  <strong>Birth date:</strong>
  <%= @member.birth_date %>
</p>

<p>
  <strong>Bloodtype:</strong>
  <%= @member.bloodtype %>
</p>

<p>
  <strong>Email:</strong>
  <%= @member.email %>
</p>

<p>
  <strong>Alarm roster:</strong>
  <%= @member.alarm_roster %>
</p>

<p>
  <strong>Attendance roster:</strong>
  <%= @member.attendance_roster %>
</p>

<p>
  <strong>Tax credit:</strong>
  <%= @member.tax_credit %>
</p>

<%= link_to 'Edit', edit_department_member_path(:department, @member) %> |
<%= link_to 'Back', department_members_path %>